version: "3.9"

services:
  angular_frontend:
    image: winderosion-cloud:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Serve Angular app on host port 80
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
